# Change these first
owner: Meta-Network # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: "API Governance"
    url: "https://governance.matataki.io/api/logs"
  - name: "API management"
    url: "https://api-mgr-hk.mttk.net"
  - name: "API Meta Network"
    url: "https://network.api.metanetwork.online"
  - name: "API MTTK"
    url: "https://api.mttk.net"
  - name: "API MTTK auth-be"
    url: "http://auth-be.mttk.net"
  - name: "API MTTK cache-ore"
    url: "http://cache-ore.mttk.net"
  - name: "API MTTK cache-ore subscriptions"
    url: "https://cache-ore.mttk.net/matataki/status/subscriptions"
  - name: "API MTTK IPFS"
    url: "https://api.mttk.net/post/ipfs/QmSr94SdMEdCgGTKyJYTwMdVEzZ28sRiLqfQ7S7c2t8C5h"
  - name: "API MTTK Token"
    url: "https://api.mttk.net/minetoken/238"
  - name: "API Quest"
    url: "https://misson-hall-api.mttk.net"
  - name: "Cryptomeetup"
    url: "https://cryptomeetup.async.moe"
  - name: "Hero"
    url: "https://dao-hero.netlify.app"
  - name: "management"
    url: "https://mgr-prod.mttk.net"
  - name: "Matataki Airdrop"
    url: "https://www.matataki-airdrop.xyz"
  - name: "Matataki DAO"
    url: "https://matataki-dao.netlify.app"
  - name: "Matataki developer"
    url: "https://developer.matataki.io"
  - name: "Matataki Doc"
    url: "https://docs.matataki.io"
  - name: "Matataki FE Article"
    url: "https://www.matataki.io/article"
  - name: "Matataki FE P"
    url: "https://www.matataki.io/p/9730"
  - name: "Matataki FE Token"
    url: "https://www.matataki.io/token/238"
  - name: "Matataki Governace"
    url: "https://governance.matataki.io"
  - name: "Matataki mining"
    url: "https://matataki-mining.netlify.app"
  - name: "Matataki NFT Market"
    url: "https://nft-market.matataki.io"
  - name: "Matataki Quest"
    url: "https://quest.matataki.io"
  - name: "MatatakiMD"
    url: "https://md.mttk.net"
  - name: "Metanetowrk Map"
    url: "https://www.metanetwork.online"
  - name: "MetaNetwork Home"
    url: "https://home.metanetwork.online"
  - name: "OSS aliyuncs cn hongkong"
    url: "https://smartsignature-img.oss-cn-hongkong.aliyuncs.com/avatar/2020/01/27/4ea1a68f7445d49f4cc36df476be2a09.jpg"
  - name: "Test Bot"
    url: "https://cstate-one.vercel.app"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: xiaotiandada.github.io
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: uptime monitor and status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
